version: '3.9'  
name: docker-workshop 

services:

  nodejs-service: 
    container_name: nodejs  
    restart: always  
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3001:3000' 
   # volumes:
     # - .:/my-app
    networks: 
      - my-network-1
    depends_on:
      - mongodb-service

  mongodb-service:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:  
      - '27018:27017'  
    volumes:
      - mongodb-volume:/data/db
    networks: 
      - my-network-1

networks:

  my-network-1:  
    driver: bridge  

volumes:

  mongodb-volume:
